FROM agrigorev/zoomcamp-model:mlops-2024-3.10.13-slim


WORKDIR /app

COPY ["Pipfile","Pipfile.lock","./"]

COPY ["starter.py", "./"]
RUN pip install pipenv
RUN pipenv install --system --deploy




CMD ["python","starter.py","yellow","2023","5"]